
For more info and how to connect from windows,
see https://docs.ycrc.yale.edu/clusters-at-yale/guides/jupyter/
MacOS or linux terminal command to create your ssh tunnel
ssh -N -f -L 9109:pn074:9109 anthony.meza@poseidon.whoi.edu
Windows MobaXterm info
Forwarded port:same as remote port Remote server: pn074
Remote port: 9109
SSH server: poseidon.whoi.edu
SSHlogin: anthony.meza
SSH port: 22
Use a Browser on your local machine to go to: localhost:9109 (prefix w/ https:// if using password) 
/vortexfs1/home/anthony.meza/GLORYS_data/1993/01/glorys_NEP_19930101.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1993/04/glorys_NEP_19930410.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1993/07/glorys_NEP_19930719.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1993/10/glorys_NEP_19931027.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1994/02/glorys_NEP_19940204.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1994/05/glorys_NEP_19940515.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1994/08/glorys_NEP_19940823.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1994/12/glorys_NEP_19941201.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1995/03/glorys_NEP_19950310.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1995/06/glorys_NEP_19950618.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1995/09/glorys_NEP_19950926.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1996/01/glorys_NEP_19960104.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1996/04/glorys_NEP_19960413.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1996/07/glorys_NEP_19960722.nc
/vortexfs1/home/anthony.meza/GLORYS_data/1996/10/glorys_NEP_19961030.nc
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/Atmospheric Rivers and Waves/CoastalWaves_Climatology.py", line 56, in <module>
    sum_climatology(fname)
  File "/vortexfs1/home/anthony.meza/Atmospheric Rivers and Waves/CoastalWaves_Climatology.py", line 50, in sum_climatology
    ds_climatology.thetao[dyidx, :, :, :] += ds.thetao[0, :, :, :]
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/dataarray.py", line 818, in __getitem__
    return self.isel(indexers=self._item_key_to_dict(key))
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/dataarray.py", line 1389, in isel
    ds = self._to_temp_dataset()._isel_fancy(
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/dataset.py", line 2464, in _isel_fancy
    new_var = var.isel(indexers=var_indexers)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/variable.py", line 1322, in isel
    return self[key]
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/variable.py", line 870, in __getitem__
    data = as_indexable(self._data)[indexer]
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/indexing.py", line 1483, in __getitem__
    result = self.array[key]
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5361, in __getitem__
    return getitem(key)
IndexError: index 365 is out of bounds for axis 0 with size 365
